### ISSUE TITLE
[App-Staff]: 多言語対応（初期リリース分）

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#140]
### 概要

```[tasklist]
### Tasks
- [ ] https://github.com/FlutterKaigi/2024/issues/141
- [ ] https://github.com/FlutterKaigi/2024/issues/142
- [ ] https://github.com/FlutterKaigi/2024/issues/143
- [ ] https://github.com/FlutterKaigi/2024/issues/144
```
