### ISSUE TITLE
[App-Staff]: CI の整備

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#194]
### 概要

```[tasklist]
### Tasks
- [ ] #271
- [ ] https://github.com/FlutterKaigi/2024/issues/273
- [ ] https://github.com/FlutterKaigi/2024/issues/274
- [ ] https://github.com/FlutterKaigi/2024/issues/275
- [ ] https://github.com/FlutterKaigi/2024/issues/350
```

### 参考文献

https://github.com/yumemi-inc/flutter-mobile-project-template
