### ISSUE TITLE
[Staff]: ストア公開までに必須

### ISSUE THREAD

**Issue by blendthink** [FlutterKaigi/2024#411]
### 関連するもの

App

### タスクの種類

Feature

```[tasklist]
### Tasks
- [ ] https://github.com/FlutterKaigi/2024/issues/231
- [ ] https://github.com/FlutterKaigi/2024/issues/412
- [ ] https://github.com/FlutterKaigi/2024/issues/413
- [ ] https://github.com/FlutterKaigi/2024/issues/36
- [ ] https://github.com/FlutterKaigi/2024/issues/375
- [ ] #434
```
